
WARDROBE_TOKEN_CHNG_AMT = 0
WARDROBE_REQUIRED_TOKEN = 0

TRYON_TOKEN_CHNG_AMT = -1
TRYON_REQUIRED_TOKEN = 1

EDIT_TOKEN_CHNG_AMT = -1
EDIT_REQUIRED_TOKEN = 1

REVIEW_TOKEN_CHNG_AMT = -1
REVIEW_REQUIRED_TOKEN = 1
